name : velocity

system matrix: [[1, 0.3333, 0     , 0      ,    0,  0     ],
                [0, 1     , 0     , 0      ,    0,  0     ],
                [0, 0     , 1     , 0.3333 ,    0,  0     ],
                [0, 0     , 0     , 1      ,    0,  0     ],
                [0, 0     , 0     , 0      ,    1,  0.3333],
                [0, 0     , 0     , 0      ,    0,  1     ]]

input matrix: [[1,0,0,0,0,0],
               [0,0,1,0,0,0],
               [0,0,0,0,1,0]]

system conv matrix: [[0.005,0,0,0,0,0],
                     [0,0.005,0,0,0,0],
                     [0,0,0.005,0,0,0],
                     [0,0,0,0.005,0,0],
                     [0,0,0,0,0.005,0],
                     [0,0,0,0,0,0.005]]
sensor conv matrix: [[20,0,0],
                     [0,20,0],
                     [0,0,20]]


